---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Nane }}frontend
  labels:
    name: {{ .Release.Name }}frontend
spec:
  replicas: {{ .Values.replicaCountFront }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}frontend
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}frontend
    spec:
      containers:
      - name: {{ .Release.Name }}frontend
        image: {{ .Values.containerFront.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: BASE_URL
          value: http://localhost:9000
        volumeMounts:
        - name: file-storage
          mountPath: /mnt
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: {{ .Values.frontVolume }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}backend
  labels:
    name: {{ .Release.Name }}backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}backend
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}backend
    spec:
      containers:
      - name: {{ .Release.Name }}backend
        image: {{ .Values.containerBack.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          value: postgres://postgres:postgres@db-service:5432/news
        volumeMounts:
        - name: file-storage
          mountPath: /mnt
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: {{ .Values.backVolume }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}db
  labels:
    name: {{ .Release.Name }}db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}db
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}db
    spec:
      containers:
      - name: {{ .Release.Name }}db
        image: {{ .Values.containerDB.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: {{ .Values.dbVolume }}

