---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}backend-service
  labels:
    name: {{ .Release.Name }}backend-service
spec:
  ports:
  - port: 9000
  selector:
    name: {{ .Release.Name }}backend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}db-service
  labels:
    name: {{ .Release.Name }}db-service
spec:
  ports:
  - port: 5432
  selector:
    name: {{ .Release.Name }}db
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}frontend-service
  labels:
    name: {{ .Release.Name }}frontend-service
spec:
  ports:
  - port: 80
  selector:
    name: {{ .Release.Name }}frontend
  type: ClusterIP
